# This is for quick development with a single command like `docker compose run --build dev`
services:
  dev:
    build:
      context: .
      tags:
        - "ghcr.io/nelsonjchen/docker-quick-llama/kaniko:devel"
        - "ghcr.io/nelsonjchen/docker-quick-llama/cache:devel"
