name: Build
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Remove .NET build tools for space:""
        run: sudo rm -rf /usr/share/dotnet
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo "Free space:"
          df -h
      - name: Run Nvidia base image to test
        run: |
          docker run --rm nvidia/cuda:11.7.1-devel-ubuntu22.04 df -h

